# 13_Question

Write a NumPy program to create an array of 7 zeros, 7 ones, 7 fives.

In [1]:
import numpy as np

In [2]:
my_zeros = np.zeros(7)

In [3]:
print(my_zeros)

[0. 0. 0. 0. 0. 0. 0.]


In [4]:
my_ones = np.ones(7)

In [5]:
print(my_ones)

[1. 1. 1. 1. 1. 1. 1.]


In [6]:
my_fives = np.ones(7)*5

In [7]:
print(my_fives)

[5. 5. 5. 5. 5. 5. 5.]
