# 16_Question_Answer

Write a NumPy program to create a 7x7 identity matrix.

In [1]:
import numpy as np

In [2]:
my_matrix = np.identity(7)

In [3]:
print(my_matrix)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
