# 20_Question_Answer

Write a NumPy program to create a 3X7 array using and iterate over it.

In [1]:
import numpy as np

In [2]:
my_array = np.arange(7,28).reshape((3,7))

In [3]:
print(my_array)

[[ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [4]:
print("Each element of the array is:")
print()
for i in np.nditer(my_array):
    print(i, end = " ")

Each element of the array is:

7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 