# 23_Question_Answer

Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 7.

In [1]:
import numpy as np

In [2]:
my_vector1 = np.random.randint(0,8,5)  # randint(low, high=None, size=None, dtype=int)

In [3]:
print("Vector of length 5 filled with arbitrary integers from 0 to 7: ", "\n",my_vector1)

Vector of length 5 filled with arbitrary integers from 0 to 7:  
 [3 0 6 7 4]


In [4]:
my_vector2 = np.random.randint(0,8,size=(2,4))

In [5]:
print("Vector of length 5 filled with arbitrary integers from 0 to 7 for size=(2,4): ", "\n",my_vector2)

Vector of length 5 filled with arbitrary integers from 0 to 7 for size=(2,4):  
 [[1 2 0 0]
 [1 4 5 4]]
