# 25_Question_Answer

Write a NumPy program to create a 3x4 matrix filled with values from 17 to 28.

In [1]:
import numpy as np

In [2]:
my_array = np.arange(17,29).reshape((3,4))

In [3]:
print(my_array)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]
