# 27_Question_Answer

Write a NumPy program to create a 7x7 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [1]:
import numpy as np

In [2]:
my_array = np.eye(7)

In [3]:
print(my_array)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
