# 31_Question_Answer

Write a NumPy program to create a 4x4x4 array filled with arbitrary values.

In [1]:
import numpy as np

In [2]:
my_array = np.random.random((4,4,4))

In [3]:
print(my_array_array)

[[[0.51082308 0.08670146 0.49089329 0.53043186]
  [0.26023231 0.0360963  0.45780937 0.88181221]
  [0.89758177 0.79506863 0.01928648 0.32084045]
  [0.35625851 0.13039633 0.89478801 0.67181151]]

 [[0.62248433 0.2880162  0.62063292 0.10926569]
  [0.5301451  0.47427382 0.58908055 0.54832619]
  [0.92643675 0.56195891 0.55821894 0.11587826]
  [0.57978822 0.64221854 0.42142165 0.8559716 ]]

 [[0.02107409 0.22656708 0.65371267 0.89770743]
  [0.70778848 0.89460372 0.2858974  0.20323595]
  [0.2146087  0.05823791 0.73892047 0.0404395 ]
  [0.90253135 0.48836975 0.22491122 0.26443887]]

 [[0.75789041 0.25694394 0.25929951 0.44466769]
  [0.90315218 0.63501601 0.94572003 0.68706172]
  [0.34849309 0.64921103 0.33780247 0.1450438 ]
  [0.70933057 0.68684355 0.3340745  0.33845873]]]
