# 34_Question_Answer

Write a NumPy program to add a vector to each row of a given matrix.

In [1]:
import numpy as np

In [2]:
my_vector = np.array([1, 2, 3])

In [3]:
print(my_vector)

[1 2 3]


In [4]:
my_matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

In [5]:
print(my_matrix)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
result = np.empty_like(my_matrix)  # Return a new array with the same shape and type as a given array.

In [7]:
for i in range(4):
    result[i, :] = my_matrix[i, :] + my_vector

In [8]:
print("Adding the vector to each row of the matrix:", "\n\n", result)

Adding the vector to each row of the matrix: 

 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


In [9]:
print(my_matrix + my_vector)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]
