# 36_Question_Answer

Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [1]:
import numpy as np
import os

In [2]:
a = np.arange(7)
b = np.arange(8,17)

In [3]:
print(a)

[0 1 2 3 4 5 6]


In [4]:
print(b)

[ 8  9 10 11 12 13 14 15 16]


In [5]:
np.savez("my_array.npz", a=a, b=b)

In [6]:
print("Load arrays from the 'my_array.npz' file: \n")
with np.load("my_array.npz") as data:
    a2 = data['a']
    b2 = data['b']
    print(a2)
    print()
    print(b2)

Load arrays from the 'my_array.npz' file: 

[0 1 2 3 4 5 6]

[ 8  9 10 11 12 13 14 15 16]
