# 37_Question_Answer

Write a NumPy program to save a given array to a text file and load it.

In [1]:
import numpy as np
import os

In [2]:
my_array = np.arange(15).reshape(5, 3)

In [3]:
print(my_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [4]:
header = "column1 column2 column3"

In [5]:
np.savetxt("my_textfile.txt", my_array, fmt="%d", header = header)

In [6]:
print("After loading, content of the text file: \n", np.loadtxt("my_textfile.txt") )

After loading, content of the text file: 
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]
