# 03_Question_Answer

Write a NumPy program to create a 3x3 matrix with values ranging from 7 to 15.

In [1]:
import numpy as np

In [2]:
my_matrix = np.arange(7,16).reshape((3,3))

In [3]:
print(my_matrix)

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
