# 10_Question_Answer

Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [1]:
import numpy as np

In [2]:
my_matrix = np.zeros((8,8),dtype=int)

In [3]:
print(my_matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [4]:
my_matrix [1::2,::2] = 1
my_matrix [::2,1::2] = 1

In [5]:
print(my_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
