# 13_Question_Answer

Write a NumPy program to create an empty and a full array.

In [1]:
import numpy as np

In [2]:
empty_array = np.empty((2,3))

In [3]:
print(empty_array)

[[-1.49166815e-154 -1.49166815e-154  1.48219694e-323]
 [ 0.00000000e+000  0.00000000e+000  4.17201348e-309]]


In [4]:
full_array = np.full((4,4),7)

In [5]:
print(full_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
